apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: vote-app
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
    # value: https://github.com/openshift-pipelines/vote-ui.git
  - name: git-repo-name
    value: $(body.repository.name)
    # value: vote-ui
  - name: git-revision
    value: $(body.head_commit.id)
    # value: master